services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: aquawatch-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
        RABBITMQ_DEFAULT_USER: aquawatch
        RABBITMQ_DEFAULT_PASS: aquawatch123
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local